import loadTemplate from '../../../utils/loadTemplate';
import baseVw from '../../baseVw';

const names = [
  'Jenn Cloud',
  'Chris Pacia',
  'Mike Greenberg',
  'Dr Washington Sanchez',
  'Daniel Zheng',
  'Jiting Song',
  'Austin Williams',
  'Ashwin Mangale',
  'Sameep Singhania',
  'Sam Patterson',
  'Juan Benet',
  'Jeromy Johnson',
  'Brian Tiger Chow',
  'ᴍᴀᴛᴛ ʙᴇʟʟ',
  'Christian Couder',
  'Henry',
  'Jakub Sztandera',
  'Richard Littauer',
  'rht',
  'Lars Gierth',
  'Tv',
  'Stephen Whitmore',
  'W. Trevor King',
  'Andreas Metsälä',
  'Mildred Ki\'Lya',
  'Knut Ahlers',
  'Tor Arne Vestbø',
  'Siraj',
  'Borzov',
  'thomas-gardner',
  'Kevin Atkinson',
  'mikey',
  'Dylan Powers',
  'Michael Muré',
  'Travis Person',
  'Konstantin Koroviev',
  'Yuval Langer',
  'Michael Lovci',
  'Friedel Ziegelmayer',
  'Tyler Smith',
  'Brian Hoffman',
  'Josh Jeffryes',
  'Robert Misiorowski',
  'Jason Hotelling',
  'Mike Wolf',
  'Monique Boediono',
  'Kirvx',
  'Squirrel2020',
  'Mario Dian',
  'rhcastilhos',
  'Libter',
  'Richard Schneider',
  'Dekker3D',
  'Aya Walraven',
  'HostFat',
  'Samuel Reed',
  'ameliagoodman',
  'Angel Leon',
  'James Wilson',
  'Justin',
  'moldcraft',
  'pryds',
  'DJ Booth',
  'Nissim Karpenstein',
  'Luca Weiss',
  'Andres Jalinton',
  'LodeRunner',
  'mpatc',
  'Hong Shuning',
  'tenthhuman',
  'David Albrecht',
  'Yuri Zhykin',
  'Leo Arias',
  'Jack Kleeman',
  'Alexander Harkness',
  'Duo Search',
  'Michael Lynch',
  'Oyebanji Jacob Mayowa',
  'Giannis Adamopoulos',
  'Steven Roose',
  'Gianluca Boiano',
  'arichnad',
  'FoxCarlos',
  'tomgalloway',
  'Nikolaos Korasidis',
  'Dustin Dettmer',
  'Tobin Harding',
  'eiabea',
  'Jondale',
  'BHC',
  'Martin Honermeyer',
  'Alex Miller',
  'Joshua Sindy',
  'unsystemizer',
  'Bartłomiej Kurzeja',
  'Daniel Gonzalez Gasull',
  'Jennifer Glauche',
  'Jonathan Cross',
  'Luigi Maselli',
  'Christopher Käck',
  'Tim Pollard',
  'Braden Glasgow',
  'Francois',
  'Dionysis Zindros',
  'Marc Schaffner-Gurney',
  'Ryan Shea',
  'Amin Shah Gilani',
  'vbuterin',
  'Mirko Bonasorte',
  'WizardOfOzzie',
  'Christian Lundkvist',
  'Ruben de Vries',
  'Steven Braeger',
  'ethers',
  'Stephan Schielke',
  'Federico Cardoso',
  'cneves',
  'Joel Lehtonen',
  'Corey Farwell',
  'Jack Peterson',
  'MiWCryptoCurrency',
  'Michael Flaxman',
  'Taylor Gerring',
  'phelixbtc',
  'genjix',
  'caedesvvv',
  'Andres Vargas',
  'Noel Maersk',
  'Bobalot',
  'ty',
];

export default class extends baseVw {
  constructor(options = {}) {
    super({
      className: 'aboutContributors',
      ...options,
    });
  }

  render() {
    loadTemplate('modals/about/contributors.html', (t) => {
      this.$el.html(t({
        names,
      }));
    });

    return this;
  }
}

